### ISSUE TITLE
bug: update quickstart for terraform 

### ISSUE THREAD

**Issue by mavogel** [aws-ia/ecs-blueprints#126]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: there is no tag yet, however this is the commit: https://github.com/aws-ia/ecs-blueprints/commit/b3179237b08929a261bd853c9933a6ac8afa00c9

- Terraform version: `Terraform v1.4.0 on darwin_arm64`

- Provider version(s): `provider registry.terraform.io/hashicorp/aws v4.58.0`

## Expected behavior

The command `cp terraform.tfvars.example terraform.tfvars` to work

## Actual behavior

```sh
cd ecs-blueprints/examples/core-infra/

terraform init

cp terraform.tfvars.example terraform.tfvars
# exit code 1
```

### Terminal Output Screenshot(s)

```console
cd ecs-blueprints/examples/core-infra
terraform init

cp terraform.tfvars.example terraform.tfvars
cp: terraform.tfvars.example: No such file or directory
```

## Additional context

the only `terraform.tfvars.example` I found was in the `backstage` folder

**Comment by mavogel** [comment]
ok I also saw `JUST FOR TESTING - DO NOT RELY ON THIS` in the module https://github.com/clowdhaus/terraform-aws-ecs/. Maybe this is still all WIP

**Comment by bryantbiggs** [comment]
docs have been updated in #128 - modules will switch back to `terraform-aws-ecs` once https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/76 is merged
