### ISSUE TITLE
lb-service from terraform blueprints fails with 'invalid function argument' and 'multiple EC2 VPCs...'

### ISSUE THREAD

**Issue by manuelbcd** [aws-ia/ecs-blueprints#135]
## Description

Following quick-start step by step I'm unable to _plan_ nor _apply_ the lb-service of the terraform blueprint. 

```
Plan: 7 to add, 0 to change, 0 to destroy.
╷
│ Error: Invalid function argument
│ 
│   on main.tf line 139, in module "ecs_service_definition":
│  139:   task_exec_iam_role_arn = one(data.aws_iam_roles.ecs_core_infra_exec_role.arns)
│     ├────────────────
│     │ while calling one(list)
│     │ data.aws_iam_roles.ecs_core_infra_exec_role.arns is set of string with 2 elements
│ 
│ Invalid value for "list" parameter: must be a list, set, or tuple value with either zero or one elements.
╵
╷
│ Error: multiple EC2 VPCs matched; use additional constraints to reduce matches to a single EC2 VPC
│ 
│   with data.aws_vpc.vpc,
│   on main.tf line 169, in data "aws_vpc" "vpc":
│  169: data "aws_vpc" "vpc" {
│ 

```
If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
`{"Modules":[{"Key":"","Source":"","Dir":"."},{"Key":"ecs_service_definition","Source":"registry.terraform.io/terraform-aws-modules/ecs/aws//modules/service","Version":"5.0.1","Dir":".terraform/modules/ecs_service_definition/modules/service"},{"Key":"ecs_service_definition.container_definition","Source":"../container-definition","Dir":".terraform/modules/ecs_service_definition/modules/container-definition"},{"Key":"service_alb","Source":"registry.terraform.io/terraform-aws-modules/alb/aws","Version":"8.6.0","Dir":".terraform/modules/service_alb"}]}%   `

- Terraform version: 1.4.6
- Provider version(s):  registry.terraform.io/hashicorp/aws v4.65.0

## Reproduction Code [Required]

- Followed quick-start step by step. 
- cd lb-service
- terraform init 
- terraform plan

## Expected behavior

Terraform plan should plan the set of actions to be reproduced

## Actual behavior

Below described error messages

### Terminal Output Screenshot(s)

```
Plan: 7 to add, 0 to change, 0 to destroy.
╷
│ Error: Invalid function argument
│ 
│   on main.tf line 139, in module "ecs_service_definition":
│  139:   task_exec_iam_role_arn = one(data.aws_iam_roles.ecs_core_infra_exec_role.arns)
│     ├────────────────
│     │ while calling one(list)
│     │ data.aws_iam_roles.ecs_core_infra_exec_role.arns is set of string with 2 elements
│ 
│ Invalid value for "list" parameter: must be a list, set, or tuple value with either zero or one elements.
╵
╷
│ Error: multiple EC2 VPCs matched; use additional constraints to reduce matches to a single EC2 VPC
│ 
│   with data.aws_vpc.vpc,
│   on main.tf line 169, in data "aws_vpc" "vpc":
│  169: data "aws_vpc" "vpc" {
│ 

```

**Comment by nvpnathan** [comment]
So the way the `core-infra` examples is designed that it's meant to be deployed once per account/region. This is why the data sources are matching more than one VPC and Execution role. Once the `core-infra` is deployed then you can deploy any number of examples on top of it.
