### ISSUE TITLE
[QUESTION] AWS will discontinue CodeStar on July 31, 2024 - how will that impact the examples here? 

### ISSUE THREAD

**Issue by codekiln** [aws-ia/ecs-blueprints#181]
#### Please describe your question here
As someone perusing and evaluating this very helpful repository and its suggested solutions, I've seen that there are some references to AWS CodeStar in the infrastructure code. After going to the docs, I see that it's changing in July: [What Is AWS CodeStar? - AWS CodeStar](https://docs.aws.amazon.com/codestar/latest/userguide/welcome.html)
> On July 31, 2024, Amazon Web Services (AWS) will discontinue support for creating and viewing AWS CodeStar projects. After July 31, 2024, you will no longer be able to access the AWS CodeStar console or create new projects. However, the AWS resources created by AWS CodeStar, including your source repositories, pipelines, and builds, will be unaffected by this change and will continue to function. AWS CodeStar Connections will not be impacted by this discontinuation.

**Will the examples continue to work after then? If not, what are the expected workarounds?**

#### Provide link to the example related to the question
* https://github.com/aws-ia/ecs-blueprints/blob/main/terraform/modules/codepipeline/main.tf#L44
* https://github.com/aws-ia/ecs-blueprints/blob/main/terraform/fargate-examples/backstage/codepipeline.tf#L55
* https://github.com/aws-ia/ecs-blueprints/blob/main/terraform/fargate-examples/graviton/codepipeline.tf#L57
* https://github.com/aws-ia/ecs-blueprints/blob/main/terraform/fargate-examples/queue-processing/codepipeline.tf#L54

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by joozero** [comment]
Like it said, those services will be unaffected by this change and will continue to function.

**Comment by joozero** [comment]
Like it said, those services will be unaffected by this change and will continue to function.
