### ISSUE TITLE
[FEATURE]Allow variable customisations for region, vpc cidr..

### ISSUE THREAD

**Issue by allamand** [aws-ia/ecs-blueprints#33]
#### Is your feature request related to a problem? Please describe

We should provide an easy way for users to change creation specifications like Region name, vpc cidr.. by providing variables with sane default

also the core-infra by default creation name is not meaningful enough, maybe have a default to ecs-blueprint-code-infra ?

**Comment by bryantbiggs** [comment]
The patterns provided are not intended to be used as modules and therefore it does not make sense to provide variables
