### ISSUE TITLE
[FEATURE] Support multiple port_mappings for the primary container

### ISSUE THREAD

**Issue by nvpnathan** [aws-ia/ecs-blueprints#74]
#### Is your feature request related to a problem? Please describe
Primary container in the ECS Service module only supports 1 port/protocol.

#### Describe the solution you'd like
ECS Service module support port_mappings map. This will allow multiple ports to be exposed on the primary container.

#### Describe alternatives you've considered
N/A

**Comment by hmalayap** [comment]
Describe the solution you'd like
ECS Service module support port_mappings map. This will allow multiple ports to be exposed on the primary container. ECS blueprints currently doesn’t support this feature.

Describe alternatives you've considered

ECS terraform  module supports multiple port mappings on the primary container. 
https://github.com/umotif-public/terraform-aws-ecs-fargate/issues/54
https://towardsaws.com/multiport-fargate-ecs-service-with-terraform-

Additional context

This feature allows applications to expose multiple ports ex: 3000 for http connectivity and 5000 for websocket connectivity. 


More information on ECS Portmappings: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html
